on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          check-latest: true

      - name: Install
        run: yarn install

      - name: Test
        run: yarn test
